---
abstract: 'Perl front end for the Gearman C library.'
author:
  - '-2010 Dennis Schoen'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-XS
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
